/**
 * Fish World — Game Data Extraction Script
 *
 * Extracts all game data constants from decompiled Udon variablesjs files
 * and outputs structured JSON files.
 *
 * Data types extracted:
 *   - Fish Index (134 species: stats, spawn rules, rarity)
 *   - Rods (17: stat multipliers, unlock requirements)
 *   - Bobbers (14: stat bonuses, unlock requirements)
 *   - Lines (9: stat bonuses, glow effects)
 *   - Enchantments (42: equipment buffs, special effects)
 *   - Boats (7 definitions: speed, boost, handling)
 *   - Boat Skins (33: cosmetics, unlock requirements)
 *   - Sea Events (10: spawn weights, luck multipliers)
 *   - Pet Companions (6: rarity, unlock requirements)
 *   - Pet Stats (1: AFK fishing upgrade costs)
 *   - Titles/Achievements (34: rewards, tracking)
 *   - Inventory Items (19: consumables, quest items)
 *   - Shop Items (23: equipment for sale)
 *   - Weather States (13: visual/audio settings)
 *   - Fishing Zones (11: zone properties)
 *   - Locations (24: audio zones)
 *   - Music Tracks (24: dynamic music system)
 *
 * Usage: node extract.js [--snapshot 02-28|03-01]
 *
 * Output: extracted/ directory with one JSON file per data type
 */

const fs = require('fs');
const path = require('path');

// ── Configuration ──

const snapshot = process.argv.includes('--snapshot') ? process.argv[process.argv.indexOf('--snapshot') + 1] : '03-01';

const BASE = path.join(__dirname, snapshot, 'autogenerated', 'programs');

if (!fs.existsSync(BASE)) {
  console.error(`ERROR: Snapshot directory not found: ${BASE}`);
  process.exit(1);
}

const OUTPUT_DIR = path.join(__dirname, 'extracted');
if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR);

// ── Data Type Definitions ──
// Each entry: { hash, fields (to extract), idField, nameField }

/* eslint-disable object-curly-spacing */
const DATA_TYPES = {
  fish: {
    hash: 'e5ac982ae96f853408a0a3ab03154882',
    label: 'Fish Index',
    fields: [
      'fishId',
      'fishName',
      'enabled',
      'rarity',
      'minWeight',
      'maxWeight',
      'minPrice',
      'maxPrice',
      'difficulty',
      'baseValue',
      'relicDropWeight',
      'catchOnce',
      'rewardsQuestItem',
      'canSpawnInFreshwater',
      'canSpawnInSaltwater',
      'canSpawnInSwampwater',
      'canSpawnInLava',
      'spawnInAnySaltwater',
      'allowedZoneIDs',
      'forbiddenZoneIDs',
      'canSpawnInDay',
      'canSpawnInNight',
      'prefersClear',
      'prefersRainy',
      'prefersStormy',
      'prefersFoggy',
      'prefersMoonrain',
      'prefersStarfog',
      'prefersSkybloom',
      'prefersDay',
      'prefersMorning',
      'prefersEvening',
      'prefersNight',
    ],
    idField: 'fishId',
    nameField: 'fishName',
    sort: 'fishId',
  },
  rods: {
    hash: '0a7fe06dcadd5694087b8c7d5bdbf8fd',
    label: 'Rods',
    fields: ['rodId', 'rodName', 'description', 'luck', 'strength', 'expertise', 'attractionRate', 'bigCatchRate', 'maxWeightKg', 'isUnlockedByDefault', 'isUnlockedFromLevel', 'unlockLevel'],
    idField: 'rodId',
    nameField: 'rodName',
    sort: 'rodId',
  },
  bobbers: {
    hash: '64ca1d317b8842b4aa7f64c0f8ef509a',
    label: 'Bobbers',
    fields: ['bobberId', 'bobberName', 'luck', 'strength', 'expertise', 'attractionRate', 'bigCatchRate', 'isUnlockedByDefault', 'isUnlockedFromLevel', 'unlockLevel'],
    idField: 'bobberId',
    nameField: 'bobberName',
    sort: 'bobberId',
  },
  lines: {
    hash: '78d79eb2888f3a2409296f3b255eff15',
    label: 'Lines',
    fields: ['lineId', 'lineName', 'luck', 'strength', 'expertise', 'attractionRate', 'bigCatchRate', 'emissionStrength', 'isUnlockedByDefault', 'isUnlockedFromLevel', 'unlockLevel'],
    idField: 'lineId',
    nameField: 'lineName',
    sort: 'lineId',
  },
  enchantments: {
    hash: '2d630e67ab832f64fb2d882bd46fb7ed',
    label: 'Enchantments',
    fields: [
      'enchantmentId',
      'enchantmentName',
      'enabled',
      'rarity',
      'equipmentType',
      'luckBonus',
      'strengthBonus',
      'expertiseBonus',
      'attractionRateBonus',
      'bigCatchRateBonus',
      'maxWeightBonus',
      'hasSpecialEffect',
      'specialEffect',
      'specialEffectValue',
    ],
    idField: 'enchantmentId',
    nameField: 'enchantmentName',
    sort: 'enchantmentId',
  },
  boats: {
    hash: '5e300410777b5d445aaaf83b9351c85b',
    label: 'Boats',
    fields: [
      'boatId',
      'boatName',
      'price',
      'boatClass',
      'boatSize',
      'maxSpeed',
      'accelerationRate',
      'decelerationRate',
      'turnSpeed',
      'boost',
      'sturdiness',
      'enableBoost',
      'boostMultiplier',
      'boostDuration',
      'boostCooldown',
      'isUnlockedByDefault',
      'isUnlockedFromLevel',
      'unlockLevel',
    ],
    idField: 'boatId',
    nameField: 'boatName',
    sort: 'boatId',
  },
  boatSkins: {
    hash: 'e7ac21947a545c14fb38c53ccfc8551d',
    label: 'Boat Skins',
    fields: ['skinId', 'skinName', 'compatibleBoatId', 'skinPrice', 'isDefaultSkin', 'isUnlockedFromLevel', 'unlockLevel', 'nonPurchaseable', 'requiredProduct', 'disabled'],
    idField: 'skinId',
    nameField: 'skinName',
    sort: 'skinId',
  },
  seaEvents: {
    hash: '25348dbaa17d1894f978aed49d59e50a',
    label: 'Sea Events',
    fields: [
      'eventRadius',
      'spawnWeight',
      'luckMultiplier',
      'rareFishChance',
      'modifierChanceMultiplier',
      'specificModifierChance',
      'boostedSizeModifierType',
      'boostedShaderModifierType',
      'boostedShaderModifierType2',
    ],
    idField: null,
    nameField: null,
    sort: null,
  },
  pets: {
    hash: 'e9bbce773b006704d8b25a8bfefb61ff',
    label: 'Pet Companions',
    fields: ['petId', 'petName', 'description', 'rarity', 'isUnlockedByDefault', 'unlockLevel'],
    idField: 'petId',
    nameField: 'petName',
    sort: 'petId',
  },
  petStats: {
    hash: '0dbc564466389c046bb966d32a787fa0',
    label: 'Pet Stats',
    fields: null, // extract all
    idField: null,
    nameField: null,
    sort: null,
  },
  titles: {
    hash: '882c4fa96b981e045bb088b77cd2feeb',
    label: 'Titles / Achievements',
    fields: [
      'achievementName',
      'achievementDescription',
      'titleColor',
      'sortOrder',
      'trackingKey',
      'requiredValue',
      'requiredProduct',
      'xpReward',
      'moneyReward',
      'luckBonus',
      'isHidden',
      'isDiscordExclusive',
    ],
    idField: 'sortOrder',
    nameField: 'achievementName',
    sort: 'sortOrder',
  },
  inventoryItems: {
    hash: '4496e61374e595c4d95e6b867ffc6e73',
    label: 'Inventory Items',
    fields: [
      'itemId',
      'itemName',
      'itemDescription',
      'itemType',
      'isStackable',
      'maxStackSize',
      'isUsable',
      'isConsumable',
      'consumableEffect',
      'consumableEffectDuration',
      'isRelic',
      'relicRarity',
      'relatedQuestIDs',
      'canBeDialogueRequirement',
    ],
    idField: 'itemId',
    nameField: 'itemName',
    sort: 'itemId',
  },
  shopItems: {
    hash: '32f0bd90c3148784cbe1853ab34bc4ca',
    label: 'Shop Items',
    fields: ['itemName', 'itemPrice', 'equipmentType', 'equipmentId', 'hideOnPurchase', 'autoCloseOnDistance', 'maxDistance'],
    idField: 'equipmentId',
    nameField: 'itemName',
    sort: 'equipmentId',
  },
  weather: {
    hash: '23d38b53ae9ef6748b433c7129a11942',
    label: 'Weather States',
    fields: [
      'configName',
      'weatherType',
      'allowedTimes',
      'enableFog',
      'fogColor',
      'fogDensityMultiplier',
      'sunColor',
      'sunIntensity',
      'ambientIntensity',
      'ambientColor',
      'environmentColor',
      'lightIntensityMultiplier',
      'skyboxFogIntensity',
      'skyboxFogHeight',
      'postProcessWeight',
      'weatherAudioVolume',
    ],
    idField: null,
    nameField: 'configName',
    sort: 'configName',
  },
  zones: {
    hash: '599716a952d78b14da20da6cbf849085',
    label: 'Fishing Zones',
    fields: ['zoneID', 'zoneName', 'zoneRadius', 'zonePriority', 'allowedWeatherTypes', 'hideWeatherEffects', 'checkInterval'],
    idField: 'zoneID',
    nameField: 'zoneName',
    sort: 'zoneID',
  },
  musicTracks: {
    hash: '5738a7400c4372c49b7cfbd34117fc3a',
    label: 'Music Tracks',
    fields: ['trackName', 'volume', 'selectionWeight', 'cooldownMinutes', 'allowedZones', 'allowedTimes', 'allowedWeather', 'isIntroTrack', 'introPriority', 'isWeatherIntroTrack'],
    idField: null,
    nameField: 'trackName',
    sort: 'trackName',
  },
};
/* eslint-enable object-curly-spacing */

// ── Parser ──

/**
 * Parse a variablesjs file and extract named fields.
 * @param {string} filePath
 * @param {string[]|null} fields - fields to extract, null = all
 * @returns {Object} key-value pairs
 */
function parseVariablesFile(filePath, fields) {
  const txt = fs.readFileSync(filePath, 'utf8');
  const result = {};

  // Match SymbolName + Value pairs
  const re = /"SymbolName": "(\w+)"[\s\S]*?"Value": ([^\n]+)/g;
  let m;
  while ((m = re.exec(txt)) !== null) {
    const name = m[1];
    const val = m[2].trim().replace(/,\s*$/, '');

    // Skip if not in requested fields
    if (fields && !fields.includes(name)) continue;
    // Skip Unity object references
    if (val.startsWith('{') || val === 'null') {
      result[name] = null;
      continue;
    }

    // Parse value
    if (val === 'true') result[name] = true;
    else if (val === 'false') result[name] = false;
    else if (val.startsWith('"') && val.endsWith('"')) result[name] = val.slice(1, -1);
    else if (val.includes('.') && !isNaN(val)) result[name] = parseFloat(val);
    else if (!isNaN(val)) result[name] = parseInt(val, 10);
    else result[name] = val;
  }

  return result;
}

/**
 * Extract all entries for a given data type.
 */
function extractType(config) {
  const dir = path.join(BASE, config.hash);
  if (!fs.existsSync(dir)) {
    console.warn(`  WARN: Directory not found: ${config.hash}`);
    return [];
  }

  const files = fs
    .readdirSync(dir)
    .filter(f => f.startsWith('variablesjs_'))
    .sort();

  const entries = [];
  for (const fn of files) {
    const data = parseVariablesFile(path.join(dir, fn), config.fields);
    // Add source file reference
    data._source = fn;
    entries.push(data);
  }

  // Sort if configured
  if (config.sort && entries.length > 0 && config.sort in entries[0]) {
    entries.sort((a, b) => {
      const av = a[config.sort];
      const bv = b[config.sort];
      if (typeof av === 'number' && typeof bv === 'number') return av - bv;
      return String(av).localeCompare(String(bv));
    });
  }

  return entries;
}

// ── Main ──

console.log('Fish World Data Extraction');
console.log(`Snapshot: ${snapshot}`);
console.log(`Source: ${BASE}`);
console.log(`Output: ${OUTPUT_DIR}\n`);

const summary = {};

for (const [key, config] of Object.entries(DATA_TYPES)) {
  process.stdout.write(`Extracting ${config.label}...`);
  const entries = extractType(config);
  const outPath = path.join(OUTPUT_DIR, `${key}.json`);
  fs.writeFileSync(outPath, JSON.stringify(entries, null, 2), 'utf8');
  console.log(` ${entries.length} entries -> ${key}.json`);
  summary[key] = { label: config.label, count: entries.length };
}

// Write summary
const summaryPath = path.join(OUTPUT_DIR, '_summary.json');
fs.writeFileSync(summaryPath, JSON.stringify(summary, null, 2), 'utf8');
console.log('\nSummary -> _summary.json');

// Print summary table
console.log(`\n${'─'.repeat(50)}`);
console.log('  Data Type               Count');
console.log(`${'─'.repeat(50)}`);
for (const [, info] of Object.entries(summary)) {
  console.log(`  ${info.label.padEnd(24)} ${String(info.count).padStart(5)}`);
}
console.log(`${'─'.repeat(50)}`);
const total = Object.values(summary).reduce((s, v) => s + v.count, 0);
console.log(`  TOTAL                   ${String(total).padStart(5)}`);
